#!/bin/bash

declare -x OWNCLOUD_IPADDRESS
declare -x OWNCLOUD_DOMAIN
declare -x OWNCLOUD_DB_TYPE
declare -x OWNCLOUD_DB_NAME
declare -x OWNCLOUD_DB_USERNAME
declare -x OWNCLOUD_DB_PASSWORD
declare -x OWNCLOUD_DB_HOST
declare -x OWNCLOUD_DB_PREFIX
declare -x OWNCLOUD_ADMIN_USERNAME
declare -x OWNCLOUD_ADMIN_PASSWORD

[[ -z "${OWNCLOUD_IPADDRESS}" ]] && OWNCLOUD_IPADDRESS=$(awk 'NR==1 {print $1}' /etc/hosts)
[[ -z "${OWNCLOUD_DOMAIN}" ]] && OWNCLOUD_DOMAIN=${HOSTNAME}
[[ -z "${OWNCLOUD_DB_TYPE}" ]] && OWNCLOUD_DB_TYPE="sqlite"
[[ -z "${OWNCLOUD_DB_NAME}" ]] && OWNCLOUD_DB_NAME="owncloud"
[[ -z "${OWNCLOUD_DB_USERNAME}" ]] && OWNCLOUD_DB_USERNAME=""
[[ -z "${OWNCLOUD_DB_PASSWORD}" ]] && OWNCLOUD_DB_PASSWORD=""
[[ -z "${OWNCLOUD_DB_HOST}" ]] && OWNCLOUD_DB_HOST=""
[[ -z "${OWNCLOUD_DB_PREFIX}" ]] && OWNCLOUD_DB_PREFIX=""
[[ -z "${OWNCLOUD_ADMIN_USERNAME}" ]] && OWNCLOUD_ADMIN_USERNAME="admin"
[[ -z "${OWNCLOUD_ADMIN_PASSWORD}" ]] && OWNCLOUD_ADMIN_PASSWORD="admin"

/usr/bin/templater -d -p owncloud \
  -o /app/config/generated.config.php \
  /etc/templates/config.php.tmpl

find /app \( \! -user apache -o \! -group apache \) -print0 | xargs -0 chown apache:apache

pushd /app > /dev/null
  if [[ ! -f /app/config/config.php ]]
  then
    CMD="/usr/bin/php occ maintenance:install --no-interaction --data-dir /app/data"

    [[ -n "${OWNCLOUD_DB_TYPE}" ]] && CMD="${CMD} --database ${OWNCLOUD_DB_TYPE}"
    [[ -n "${OWNCLOUD_DB_NAME}" ]] && CMD="${CMD} --database-name ${OWNCLOUD_DB_NAME}"
    [[ -n "${OWNCLOUD_DB_USERNAME}" ]] && CMD="${CMD} --database-user ${OWNCLOUD_DB_USERNAME}"
    [[ -n "${OWNCLOUD_DB_PASSWORD}" ]] && CMD="${CMD} --database-pass ${OWNCLOUD_DB_PASSWORD}"
    [[ -n "${OWNCLOUD_DB_HOST}" ]] && CMD="${CMD} --database-host ${OWNCLOUD_DB_HOST}"
    [[ -n "${OWNCLOUD_DB_PREFIX}" ]] && CMD="${CMD} --database-table-prefix ${OWNCLOUD_DB_PREFIX}"
    [[ -n "${OWNCLOUD_ADMIN_USERNAME}" ]] && CMD="${CMD} --admin-user ${OWNCLOUD_ADMIN_USERNAME}"
    [[ -n "${OWNCLOUD_ADMIN_PASSWORD}" ]] && CMD="${CMD} --admin-pass ${OWNCLOUD_ADMIN_PASSWORD}"

    echo "Installing with: ${CMD}"
    /sbin/su-exec \
      apache \
      ${CMD}
  else
    CMD="/usr/bin/php occ upgrade --skip-migration-test --no-interaction"

    echo "Upgrading with: ${CMD}"
    /sbin/su-exec \
      apache \
      ${CMD}
  fi

  /sbin/su-exec \
    apache \
    /usr/bin/php \
    occ \
    background:cron \
    --no-interaction
popd > /dev/null
